# Generated by Kelly Lwin _ Feb 16th 2026 (4)

import json

ground_truth = {
    "clip_000": 0,
    "clip_001": 1,
}

correct = 0
total = 0

with open("results.txt") as f:
    for line in f:
        clip, output = line.split(": ", 1)
        pred = json.loads(output)["stability"]
        if ground_truth[clip] == pred:
            correct += 1
        total += 1

print("Accuracy:", correct / total)
