# Generated by Kelly Lwin _ Feb 16th 2026 (2)

import cv2
import os

input_folder = "clips"
output_folder = "frames"
frames_per_clip = 5

os.makedirs(output_folder, exist_ok=True)

for clip in os.listdir(input_folder):
    clip_path = os.path.join(input_folder, clip)
    cap = cv2.VideoCapture(clip_path)

    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    interval = total_frames // frames_per_clip

    clip_name = clip.replace(".mp4", "")
    clip_frame_dir = os.path.join(output_folder, clip_name)
    os.makedirs(clip_frame_dir, exist_ok=True)

    for i in range(frames_per_clip):
        cap.set(cv2.CAP_PROP_POS_FRAMES, i * interval)
        ret, frame = cap.read()
        if ret:
            cv2.imwrite(os.path.join(clip_frame_dir, f"frame_{i}.jpg"), frame)

    cap.release()
