# Generated by Kelly Lwin _ Feb 16th 2026

from moviepy.video.io.VideoFileClip import VideoFileClip
import os

input_path = "p63_front_1.mp4" # 5min 48seconds
output_dir = "clips_2"
clip_length = 30 # seconds

os.makedirs(output_dir, exist_ok=True)

video = VideoFileClip(input_path)
duration = int(video.duration)

clip_index = 0
for start in range(0, duration, clip_length):
    end = min(start + clip_length, duration)
    clip = video.subclipped(start, end)
    clip.write_videofile(
        os.path.join(output_dir, f"clip_{clip_index:03d}.mp4"),
        codec="libx264",
        audio=False
    )
    clip_index += 1

video.close()